# Generated by Django 2.2.7 on 2019-11-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0008_auto_20191127_0834'),
        ('page', '0002_auto_20191129_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Slider',
            field=models.ManyToManyField(to='slider.Slider'),
        ),
    ]
