# Generated by Django 2.2.7 on 2019-11-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_home_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Description',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='Title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
