# Generated by Django 2.2.7 on 2019-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20191129_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='default', unique=False),
            preserve_default=False,
        ),
    ]
