# Generated by Django 2.2.7 on 2019-11-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
