# Generated by Django 2.2.7 on 2019-12-10 10:16

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20191129_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Content',
            field=djrichtextfield.models.RichTextField(default='default'),
            preserve_default=False,
        ),
    ]
