# Generated by Django 2.2.7 on 2019-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.ImageField(upload_to='Images/Services')),
                ('Title', models.CharField(max_length=100)),
                ('Heading', models.CharField(max_length=100)),
                ('Sub_Heading', models.CharField(max_length=100)),
                ('Main_Text', models.TextField()),
            ],
        ),
    ]
