# Generated by Django 2.2.7 on 2019-11-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20191126_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_src',
            old_name='src',
            new_name='label_1',
        ),
    ]
