# Generated by Django 2.2.7 on 2019-11-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20191126_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_src',
            old_name='label_1',
            new_name='Image_Large',
        ),
        migrations.RenameField(
            model_name='image_src',
            old_name='label_2',
            new_name='label_Medium',
        ),
        migrations.RenameField(
            model_name='image_src',
            old_name='label_3',
            new_name='label_Small',
        ),
    ]
