# Generated by Django 2.2.7 on 2019-11-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_auto_20191127_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_src',
            old_name='label_Medium',
            new_name='Image_Medium',
        ),
        migrations.RenameField(
            model_name='image_src',
            old_name='label_Small',
            new_name='Image_Small',
        ),
    ]
