# Generated by Django 2.2.7 on 2019-11-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0006_auto_20191127_0751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Src',
            new_name='Slider',
        ),
    ]
