# Generated by Django 2.2.7 on 2019-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0007_auto_20191127_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Image_Large',
            field=models.ImageField(upload_to='Images/Slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image_Medium',
            field=models.ImageField(upload_to='Images/Slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image_Small',
            field=models.ImageField(upload_to='Images/Slider'),
        ),
    ]
