# Generated by Django 2.2.7 on 2019-12-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0008_auto_20191127_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Title',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image_Large',
            field=models.ImageField(upload_to='static/Images/Slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image_Medium',
            field=models.ImageField(upload_to='static/Images/Slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image_Small',
            field=models.ImageField(upload_to='static/Images/Slider'),
        ),
    ]
