# Generated by Django 2.2.7 on 2019-12-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0009_auto_20191202_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
    ]
