# Generated by Django 2.2.7 on 2019-12-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
